import React from 'react';
import {Form} from 'antd';
import { Link, Route, Routes } from 'react-router-dom';
import '../styles/PassportAnalysisStyles.css';

import Query1 from './Query1';
import Query2 from './Query2';
import Query3 from './Query3';
import Query4 from './Query4';

const PassportAnalysis = () => {
  return (
    <div className="passport-analysis-container">
      <div className="passport-analysis-queries">
        <div className="passport-analysis-heading">
          <img src="/images/emblem.jpg" alt="Indian Emblem 1" />
          <h1>Passport Analysis</h1>
          <img src="/images/emblem.jpg" alt="Indian Emblem 2" />
        </div>
        <h2>Select a Query:</h2>
        <ol>
          <li>
            <Link to="/query1">Between any two years, list out passport number and names of a kendra with adult or kid and male or female.</Link>
          </li>
          <li>
            <Link to="/query2">Between any two years, give the passport issue count for every kendra in descending order.</Link>
          </li>
          <li>
            <Link to="/query3">Between any two years, give revenue generated by all kendras.</Link>
          </li>
          <li>
            <Link to="/query4">Between any two years, give the count of top k kendras of tatkal passport issued in descending order.</Link>
          </li>
        </ol>
        <Form.Item className="back-to-home">
        <Link to="/">Back to Home</Link>
      </Form.Item>
      </div>
      <div>
        <Routes>
          <Route path="/query1" element={<Query1 />} />
          <Route path="/query2" element={<Query2 />} />
          <Route path="/query3" element={<Query3 />} />
          <Route path="/query4" element={<Query4 />} />
        </Routes>
        
      </div>
      
      
    </div>
  );
};

export default PassportAnalysis;
