import React, { useState } from 'react';
import { Form, DatePicker, Button } from 'antd';
import { Link } from 'react-router-dom';
import '../styles/Query3Styles.css';

const Query3 = () => {
  const [form] = Form.useForm();
  const [queryResult, setQueryResult] = useState([]);

  const onFinish = async (values) => {
    console.log('Received values:', values);

    try {
      const response = await fetch(`/api/query3?startDate=${values.startDate.format('YYYY-MM-DD')}&endDate=${values.endDate.format('YYYY-MM-DD')}`);
      const data = await response.json();
      setQueryResult(data);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div className="query3-container">
    <div className="query3-sub">
      <h2>Query 3: Revenue generated by each kendra</h2>
      <Form form={form} onFinish={onFinish}>
        <Form.Item name="startDate" label="Start Date" >
          <DatePicker style={{ width: '100%' }} />
        </Form.Item>
        <Form.Item name="endDate" label="End Date" >
          <DatePicker style={{ width: '100%' }} />
        </Form.Item>
        <Form.Item>
          <Button type="primary" htmlType="submit">
            Submit
          </Button>
        </Form.Item>
        <Form.Item>
            <Link to="/passport-analysis">Select a query</Link>
          </Form.Item>
      </Form>

      {queryResult.length > 0 && (
        <div className="query-result">
          <h3>Query Result:</h3>
          <table>
            <thead>
              <tr>
                <th>Kendra</th>
                <th>Revenue</th>
              </tr>
            </thead>
            <tbody>
              {queryResult.map((resultItem) => (
                <tr key={resultItem._id}>
                  <td>{resultItem._id}</td>
                  <td>{resultItem.revenue}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
    </div>
  );
};

export default Query3;
